AWSTemplateFormatVersion: "2010-09-09"

Description: Ec2 instance creation with t3.large
Parameters:
  InstanceType:
    Description: AWS EC2 instance type
    Type: String
    Default: t3.large
  ImageId:    
    Type: String
    Default: 'ami-0c02fb55956c7d316'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      ImageId: !Ref 'ImageId'
  
Outputs:
  EC2Instance:
    Value: !Ref EC2Instance
    Description: EC2Instance creation
    Export: 
      Name: MyEc2Instance






