AWSTemplateFormatVersion: 2010-09-09
Description: S3_Bucket Creation
Parameters:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation    
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: '!Ref MyS3Bucket'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules: 
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: S3Bucket Name
    Export: 
      Name: MyS3BucketName                
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: S3Bucket Arn
    Export: 
      Name: MyS3BucketArn